#ifndef PUSH_H
#define PUSH_H

#include <iostream>
#include <string>

//struct generated by chatGPT, changed it to a class and also changed overload from << to |

std::string force = "\n";

class Push {
	public:
	    template<typename T>
	    Push& operator|(const T& v) {
	        std::cout << v;
	        return *this;
	    }
		
};

extern Push push;   // declaration only

#endif
