#ifndef PUSH_H
#define PUSH_H

#include <iostream>

//struct generated by chatGPT
struct Push {
    template<typename T>
    Push& operator<<(const T& v) {
        std::cout << v;
        return *this;
    }
};

extern Push push;   // declaration only

#endif
